// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.ConsentService.ConsoleSample.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConsentGroupMember
    {
        /// <summary>
        /// Initializes a new instance of the ConsentGroupMember class.
        /// </summary>
        public ConsentGroupMember()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsentGroupMember class.
        /// </summary>
        /// <param name="roles">Possible values include: 'none', 'read',
        /// 'write', 'delete', 'all'</param>
        public ConsentGroupMember(string key = default(string), string name = default(string), System.Guid? subscriptionId = default(System.Guid?), string roles = default(string))
        {
            Key = key;
            Name = name;
            SubscriptionId = subscriptionId;
            Roles = roles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'none', 'read', 'write',
        /// 'delete', 'all'
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        public string Roles { get; set; }

    }
}
