// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.ConsentService.ConsoleSample.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MemberConsentResponse
    {
        /// <summary>
        /// Initializes a new instance of the MemberConsentResponse class.
        /// </summary>
        public MemberConsentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MemberConsentResponse class.
        /// </summary>
        public MemberConsentResponse(System.Guid? consentGroupId = default(System.Guid?), string key = default(string), string member = default(string), IList<string> scopes = default(IList<string>))
        {
            ConsentGroupId = consentGroupId;
            Key = key;
            Member = member;
            Scopes = scopes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consentGroupId")]
        public System.Guid? ConsentGroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "member")]
        public string Member { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

    }
}
