// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Consent.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConsentRolesRequestResponse
    {
        /// <summary>
        /// Initializes a new instance of the ConsentRolesRequestResponse
        /// class.
        /// </summary>
        public ConsentRolesRequestResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsentRolesRequestResponse
        /// class.
        /// </summary>
        public ConsentRolesRequestResponse(bool? canRead = default(bool?), bool? canWrite = default(bool?), bool? canDelete = default(bool?))
        {
            CanRead = canRead;
            CanWrite = canWrite;
            CanDelete = canDelete;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canRead")]
        public bool? CanRead { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canWrite")]
        public bool? CanWrite { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canDelete")]
        public bool? CanDelete { get; set; }

    }
}
