// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Consent.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConsentInstance
    {
        /// <summary>
        /// Initializes a new instance of the ConsentInstance class.
        /// </summary>
        public ConsentInstance()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsentInstance class.
        /// </summary>
        public ConsentInstance(System.Guid? id = default(System.Guid?), System.Guid? consentGroupId = default(System.Guid?), string key = default(string), IList<string> scopes = default(IList<string>), IList<string> authorizedMembers = default(IList<string>))
        {
            Id = id;
            ConsentGroupId = consentGroupId;
            Key = key;
            Scopes = scopes;
            AuthorizedMembers = authorizedMembers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consentGroupId")]
        public System.Guid? ConsentGroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authorizedMembers")]
        public IList<string> AuthorizedMembers { get; set; }

    }
}
